# Generated by Django 2.2.7 on 2021-07-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210712_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_detail',
            field=models.CharField(default=1, max_length=50, verbose_name='العنوان بالتفصيل :'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='دكتور ؟'),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='google',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_phone',
            field=models.CharField(default=1, max_length=50, verbose_name='الهاتف :'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='specialist_doctor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='متخصص في ؟'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subtitle',
            field=models.CharField(default=1, max_length=50, verbose_name=' نبذه عنك :'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='waiting_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مده الانتظار :'),
        ),
        migrations.AddField(
            model_name='profile',
            name='working_hours',
            field=models.CharField(default=1, max_length=50, verbose_name='عدد ساعات العمل :'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='who_i',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='نبذه عني :'),
        ),
    ]
