# Generated by Django 2.2.7 on 2021-07-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_type_of_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(default=1, max_length=50, verbose_name='اللقب :'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, choices=[('جلدية', 'جلدية')], max_length=50, null=True, verbose_name='دكتور ؟'),
        ),
    ]
