# Generated by Django 2.2.7 on 2021-09-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210715_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, choices=[('أسنان', 'أسنان'), ('جراحة أوعية دموية', 'جراحة أوعية دموية'), ('عظام', 'عظام'), ('علاج طبيعي وأصابات ملاعب', 'علاج طبيعي وأصابات ملاعب'), ('أورام', 'أورام'), ('تخسيس وتغذية', 'تخسيس وتغذية'), ('قلب وأوعيه دموية', 'قلب وأوعيه دموية'), ('مخ وأعصاب', 'مخ وأعصاب'), ('أنف وأذن وحنجرة', 'أنف وأذن وحنجرة'), ('جراحة أورام', 'جراحة أورام'), ('جراحة تجميل', 'جراحة تجميل'), ('أطفال حديثي الولادة', 'أطفال حديثي الولادة'), ('نساء وتوليد', 'نساء وتوليد'), ('باطنة', 'باطنة'), ('جراحة سمنة ومناظير', 'جراحة سمنة ومناظير'), ('جراحة أطفال', 'جراحة أطفال'), ('جلدية', 'جلدية'), ('أمراض دم', 'أمراض دم')], max_length=50, null=True, verbose_name='دكتور ؟'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialist_doctor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='متخصص في ؟'),
        ),
    ]
